name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create zip
        run: |
          cd custom_components/indosat_hifi_air
          zip -r ../../indosat_hifi_air.zip .

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: indosat_hifi_air.zip
          generate_release_notes: true
